
services:
  backend:
    build: ./todo-api
    container_name: todo-backend
    ports:
      - "8000:8000"
    volumes:
      - ./todo-api:/var/www/html
      - /var/www/html/vendor
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=todo
      - DB_USERNAME=test
      - DB_PASSWORD=test
      - DB_SOCKET=
    depends_on:
      - db

  frontend:
    build: ./todo-app
    container_name: todo-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api/
    volumes:
      - ./todo-app:/app
      - /app/node_modules
    depends_on:
      - backend

  db:
    image: mysql:8
    container_name: todo-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - "3307:3306"